version: '3.8'

services:
  backend:
    build: ./backend
    container_name: smart-radar-backend
    restart: always
    expose:
      - "8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: smart-radar-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
