"""
Image Search Service with configurable providers (SerpAPI or Google Custom Search)
"""
import logging
import requests
from typing import Optional, Dict, Any, List
from urllib.parse import urlparse
from uuid import uuid4
from datetime import datetime
import os
try:
    import magic
    _MAGIC_AVAILABLE = True
except ImportError:
    _MAGIC_AVAILABLE = False

from core.config import settings
from services.s3_service import s3_service

logger = logging.getLogger(__name__)


class ImageSearchService:
    """Service for searching and downloading images using configurable providers"""

    # Configurable constants
    GOOGLE_IMG_SIZE = "medium"  # Options: icon, small, medium, large, xlarge, xxlarge, huge

    def __init__(self):
        """Initialize Image Search Service"""
        self.provider = settings.image_search_provider
        self.serpapi_key = settings.serpapi_key
        self.google_api_key = settings.google_custom_search_api_key
        self.google_cx = settings.google_custom_search_engine_id

        logger.info(f"Image search service initialized with provider: {self.provider}")

    async def search_image(self, search_term: str, tenant_id: str) -> Optional[Dict[str, Any]]:
        """
        Search for an image using configured provider and download the first result

        Args:
            search_term: The search term generated by AI
            tenant_id: Tenant ID for file storage

        Returns:
            Dictionary with image info (media_id, url, filename) or None if failed
        """
        if not search_term or not search_term.strip():
            logger.warning("Empty search term provided")
            return None

        # Route to the appropriate provider
        if self.provider == "google_custom_search":
            return await self._search_with_google_custom_search(search_term, tenant_id)
        elif self.provider == "serpapi":
            return await self._search_with_serpapi(search_term, tenant_id)
        else:
            logger.error(f"Unknown image search provider: {self.provider}")
            return None

    async def search_images_urls(self, search_term: str, num_results: int = 5) -> List[Dict[str, Any]]:
        """
        Search for images and return URLs without downloading

        Args:
            search_term: The search query
            num_results: Number of results to return (default 5)

        Returns:
            List of dictionaries with image info (url, title, source, thumbnail)
        """
        if not search_term or not search_term.strip():
            logger.warning("Empty search term provided")
            return []

        # Route to the appropriate provider
        if self.provider == "google_custom_search":
            return await self._search_urls_with_google_custom_search(search_term, num_results)
        elif self.provider == "serpapi":
            return await self._search_urls_with_serpapi(search_term, num_results)
        else:
            logger.error(f"Unknown image search provider: {self.provider}")
            return []

    async def _search_urls_with_google_custom_search(self, search_term: str, num_results: int) -> List[Dict[str, Any]]:
        """
        Search for images using Google Custom Search API and return URLs

        Args:
            search_term: The search query
            num_results: Number of results to return

        Returns:
            List of image result dictionaries
        """
        if not self.google_api_key or not self.google_cx:
            logger.error("Google Custom Search API key or Search Engine ID not configured")
            return []

        try:
            # Google Custom Search API v1 endpoint
            url = "https://www.googleapis.com/customsearch/v1"

            # Google Custom Search API allows max 10 results per request
            num = min(num_results, 10)

            params = {
                "key": self.google_api_key,
                "cx": self.google_cx,
                "q": search_term,
                "rights": "cc_publicdomain,cc_attribute,cc_sharealike,cc_noncommercial,cc_nonderived",
                "imgSize": self.GOOGLE_IMG_SIZE,
                "searchType": "image",
                "num": num,
                "safe": "active",
            }

            logger.info(f"Searching Google Custom Search for: '{search_term}' (num={num})")
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()

            result = response.json()

            # Check for errors
            if "error" in result:
                error_msg = result['error'].get('message', 'Unknown error')
                logger.error(f"Google Custom Search error: {error_msg}")
                return []

            # Extract images from the response
            items = result.get("items", [])

            if not items:
                logger.warning(f"No images found for search term: '{search_term}'")
                return []

            # Format results
            search_results = []
            for item in items:
                image_url = item.get("link")
                if not image_url:
                    continue

                # Get image metadata
                image_data = item.get("image", {})

                search_results.append({
                    "url": image_url,
                    "title": item.get("title", ""),
                    "source": item.get("displayLink", ""),
                    "thumbnail": image_data.get("thumbnailLink", image_url),
                    "width": image_data.get("width"),
                    "height": image_data.get("height"),
                    "context_link": image_data.get("contextLink", "")
                })

            logger.info(f"Found {len(search_results)} images for '{search_term}'")
            return search_results

        except requests.RequestException as e:
            logger.error(f"Google Custom Search API request failed: {e}")
            return []
        except Exception as e:
            logger.error(f"Image URL search failed for '{search_term}': {e}")
            return []

    async def _search_urls_with_serpapi(self, search_term: str, num_results: int) -> List[Dict[str, Any]]:
        """
        Search for images using SerpAPI and return URLs

        Args:
            search_term: The search query
            num_results: Number of results to return

        Returns:
            List of image result dictionaries
        """
        if not self.serpapi_key:
            logger.error("SerpAPI key not configured")
            return []

        try:
            from serpapi import GoogleSearch

            search = GoogleSearch({
                "q": search_term,
                "tbm": "isch",  # Image search
                "num": num_results,
                "api_key": self.serpapi_key
            })

            result = search.get_dict()

            if "error" in result:
                logger.error(f"SerpAPI error: {result['error']}")
                return []

            # Extract images from the response
            images_results = result.get("images_results", [])

            if not images_results:
                logger.warning(f"No images found for search term: '{search_term}'")
                return []

            # Format results
            search_results = []
            for img in images_results[:num_results]:
                search_results.append({
                    "url": img.get("original", ""),
                    "title": img.get("title", ""),
                    "source": img.get("source", ""),
                    "thumbnail": img.get("thumbnail", ""),
                })

            logger.info(f"Found {len(search_results)} images for '{search_term}'")
            return search_results

        except Exception as e:
            logger.error(f"SerpAPI image URL search failed for '{search_term}': {e}")
            return []

    async def _search_with_google_custom_search(self, search_term: str, tenant_id: str) -> Optional[Dict[str, Any]]:
        """
        Search for images using Google Custom Search API v1

        Args:
            search_term: The search term
            tenant_id: Tenant ID for file storage

        Returns:
            Dictionary with image info or None if failed
        """
        if not self.google_api_key or not self.google_cx:
            logger.error("Google Custom Search API key or Search Engine ID not configured")
            return None

        try:
            # Google Custom Search API v1 endpoint
            url = "https://www.googleapis.com/customsearch/v1"

            params = {
                "key": self.google_api_key,
                "cx": self.google_cx,
                "q": search_term,
                "rights": "cc_publicdomain,cc_attribute,cc_sharealike,cc_noncommercial,cc_nonderived",
                "imgSize": self.GOOGLE_IMG_SIZE,
                "searchType": "image",  # Image search
                "num": 5,  # Number of results (max 10)
                "safe": "active",  # Safe search
            }

            logger.info(f"Searching Google Custom Search for: '{search_term}'")
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()

            result = response.json()

            # Check for errors
            if "error" in result:
                logger.error(f"Google Custom Search error: {result['error']}")
                return None

            # Extract images from the response
            items = result.get("items", [])

            if not items:
                logger.warning(f"No images found for search term: '{search_term}'")
                return None

            # Try to download the first few images until one succeeds
            for item in items[:3]:  # Try up to 3 images
                try:
                    image_url = item.get("link")
                    title = item.get("title", "")
                    source = item.get("displayLink", "")

                    # Get additional image metadata if available
                    image_data = item.get("image", {})
                    context_link = image_data.get("contextLink", "")

                    if not image_url:
                        continue

                    logger.info(f"Attempting to download image: {image_url}")

                    # Download and store the image
                    downloaded_image = await self._download_and_store_image(
                        image_url=image_url,
                        search_term=search_term,
                        tenant_id=tenant_id,
                        title=title,
                        source=source
                    )

                    if downloaded_image:
                        logger.info(f"Successfully downloaded image: {downloaded_image['url']}")
                        return downloaded_image

                except Exception as e:
                    logger.warning(f"Failed to download image from {image_url}: {e}")
                    continue

            logger.warning(f"Failed to download any images for search term: '{search_term}'")
            return None

        except requests.RequestException as e:
            logger.error(f"Google Custom Search API request failed: {e}")
            return None
        except Exception as e:
            logger.error(f"Image search failed for '{search_term}': {e}")
            return None

    async def _search_with_serpapi(self, search_term: str, tenant_id: str) -> Optional[Dict[str, Any]]:
        """
        Search for images using SerpAPI (legacy provider)

        Args:
            search_term: The search term
            tenant_id: Tenant ID for file storage

        Returns:
            Dictionary with image info or None if failed
        """
        if not self.serpapi_key:
            logger.error("SerpAPI key not configured")
            return None

        try:
            # Use SerpAPI to search for images
            from serpapi.google_search import GoogleSearch

            search = GoogleSearch({
                "q": search_term,
                "tbm": "isch",  # Image search
                "num": 5,  # Get a few results to have options
                "api_key": self.serpapi_key
            })

            result = search.get_dict()

            if "error" in result:
                logger.error(f"SerpAPI error: {result['error']}")
                return None

            # Extract images from the response
            images_results = result.get("images_results", [])

            if not images_results:
                logger.warning(f"No images found for search term: '{search_term}'")
                return None

            # Try to download the first few images until one succeeds
            for img in images_results[:3]:  # Try up to 3 images
                try:
                    original_url = img.get("original")
                    title = img.get("title", "")
                    source = img.get("source", "")

                    if not original_url:
                        continue

                    logger.info(f"Attempting to download image: {original_url}")

                    # Download and store the image
                    downloaded_image = await self._download_and_store_image(
                        image_url=original_url,
                        search_term=search_term,
                        tenant_id=tenant_id,
                        title=title,
                        source=source
                    )

                    if downloaded_image:
                        logger.info(f"Successfully downloaded image: {downloaded_image['url']}")
                        return downloaded_image

                except Exception as e:
                    logger.warning(f"Failed to download image from {original_url}: {e}")
                    continue

            logger.warning(f"Failed to download any images for search term: '{search_term}'")
            return None

        except Exception as e:
            logger.error(f"Image search failed for '{search_term}': {e}")
            return None

    async def _download_and_store_image(
        self,
        image_url: str,
        search_term: str,
        tenant_id: str,
        title: str = "",
        source: str = ""
    ) -> Optional[Dict[str, Any]]:
        """Download image and store it using the same logic as upload_media_from_url"""
        try:
            # Download image from URL (same logic as upload_media_from_url in media.py)
            response = requests.get(image_url, timeout=10, headers={
                'User-Agent': 'OmniPush/1.0'
            })
            response.raise_for_status()

            # Validate content type
            content_type = response.headers.get('content-type', '').lower()
            if not content_type.startswith('image/'):
                logger.warning(f"URL does not point to a valid image: {image_url}")
                return None

            if content_type not in settings.allowed_file_types:
                logger.warning(f"Image type {content_type} not supported: {image_url}")
                return None

            file_content = response.content

            # Validate file size
            if len(file_content) > settings.max_file_size:
                logger.warning(f"Image too large: {len(file_content)} bytes")
                return None

            # Generate filename
            parsed_url = urlparse(image_url)
            filename = os.path.basename(parsed_url.path)
            if not filename or '.' not in filename:
                # Create filename based on content type
                ext_map = {
                    'image/jpeg': 'jpg',
                    'image/jpg': 'jpg',
                    'image/png': 'png',
                    'image/gif': 'gif',
                    'image/webp': 'webp'
                }
                ext = ext_map.get(content_type, 'jpg')
                filename = f"auto_search_{uuid4().hex[:8]}.{ext}"

            # Validate file content type
            if _MAGIC_AVAILABLE:
                detected_type = magic.from_buffer(file_content, mime=True)
                if detected_type not in settings.allowed_file_types:
                    logger.warning(f"Invalid image content detected: {detected_type}")
                    return None
            else:
                # Fall back to HTTP content-type header (already validated above)
                detected_type = content_type

            media_id = str(uuid4())

            # Save to S3 storage (same logic as save_file_to_storage)
            try:
                upload_result = await s3_service.upload_file(
                    file_content,
                    filename,
                    tenant_id,
                    media_type="auto_images",  # Separate folder for auto-downloaded images
                    metadata={
                        'uploaded_via': 'auto_image_search',
                        'search_term': search_term,
                        'source_url': image_url,
                        'title': title,
                        'source': source,
                        'media_id': media_id
                    }
                )

                file_url = upload_result['url']
                s3_key = upload_result['key']

                logger.info(f"Auto-downloaded image uploaded to S3: {file_url}")

                return {
                    'media_id': media_id,
                    'url': file_url,
                    'filename': filename,
                    's3_key': s3_key,
                    'file_size': len(file_content),
                    'content_type': content_type,
                    'attribution': {
                        'source': 'google_images',
                        'search_term': search_term,
                        'source_url': image_url,
                        'title': title,
                        'original_source': source
                    }
                }

            except Exception as s3_error:
                logger.error(f"Failed to upload auto-downloaded image to S3: {s3_error}")
                return None

        except requests.RequestException as e:
            logger.warning(f"Failed to download image from URL {image_url}: {e}")
            return None
        except Exception as e:
            logger.error(f"Failed to download and store image from {image_url}: {e}")
            return None


# Singleton instance
image_search_service = ImageSearchService()